apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cowin-frontend
  name: cowin-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cowin-frontend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cowin-frontend
    spec:
      containers:
      - image: gcr.io/cowin-slot-313213/github.com/debashish345/cowin-mail-notifier
        imagePullPolicy: IfNotPresent
        name: cowin-frontend
